"""The Devon Coffee Company scraper implementation with Shopify JSON extraction."""

import logging

from .registry import register_scraper
from .shopify_base import ShopifyJsonScraper

logger = logging.getLogger(__name__)


@register_scraper(
    name="devon-coffee-company",
    display_name="The Devon Coffee Company",
    roaster_name="The Devon Coffee Company",
    website="https://devoncoffeecompany.com",
    description="Specialty coffee roaster based in Devon, England, roasting 100% "
    "certified organic coffees for home and wholesale",
    requires_api_key=True,
    currency="GBP",
    country="United Kingdom",
    status="available",
)
class DevonCoffeeCompanyScraper(ShopifyJsonScraper):
    """Scraper for The Devon Coffee Company (devoncoffeecompany.com) using Shopify products.json."""

    def __init__(self, api_key: str | None = None):
        """Initialize The Devon Coffee Company scraper.

        Args:
            api_key: Google API key for Gemini. If None, will try environment variable.
        """
        super().__init__(
            roaster_name="The Devon Coffee Company",
            base_url="https://devoncoffeecompany.com",
            products_json_urls=["https://devoncoffeecompany.com/collections/home-coffee/products.json"],
            scrape_product_pages=False,
            cache_product_pages=False,
            rate_limit_delay=2.0,
            max_retries=3,
            timeout=30.0,
            use_optimized_mode=True,
        )

        # Exclude non-coffee products (subscriptions, gift cards, equipment, etc.)
        self.exclude_slugs = [
            "subscription",
            "gift-card",
            "gift",
            "wholesale",
            "equipment",
            "brewing",
            "accessory",
            "merchandise",
        ]

        if api_key:
            from ..ai import CoffeeDataExtractor

            self.ai_extractor = CoffeeDataExtractor(api_key=api_key)

    def preprocess_product_url(self, url: str) -> str:
        """Standardize product URLs to the site's canonical /products/<handle> form.

        The storefront links to products without the collection segment, so
        strip the collection path generated by ShopifyJsonScraper.
        """
        if "/collections/" in url and "/products/" in url:
            idx = url.find("/products/")
            return f"{url[:url.find('/collections/')]}{url[idx:]}"
        return url
